### ISSUE TITLE
Maintain `linter-puppet-lint`

### ISSUE THREAD

**Issue by keplersj** [rafitadiaz/linter-puppet-lint-for-linter-3#1]
If you would like, you may maintain [AtomLinter/linter-puppet-lint](https://github.com/AtomLinter/linter-puppet-lint) with the permission of @steelbrain and one of @AtomLinter/owners.

**Comment by rafitadiaz** [comment]
I would like.
I using it at work and I now I am improving it with support to enable/disable individual checks and fixing the column problem. And probably I develop other to puppet parser validate command.

**Comment by keplersj** [comment]
It is very helpful to know that you use Puppet yourself and depend on it for your job. If you wouldn't mind chiming in at AtomLinter/linter-puppet-lint#15 we should be able to get this moving.

**Comment by rafitadiaz** [comment]
Done!
